import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const builtins = [...builtinModules, ...builtinModules.map((mod) => `node:${mod}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === "production";

// Optional extra origin for dev builds (a local Whimsical server), added to
// the plugin's recognized origins at build time. Release builds never set
// this, so the value ships only in builds the developer makes locally.
const devOrigin = process.env.WHIMSICAL_DEV_ORIGIN;

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  define: devOrigin
    ? { __WHIMSICAL_DEV_ORIGIN__: JSON.stringify(devOrigin) }
    : {},
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
